---
abstract: 'a mod_perl based http proxy base class'
author:
  - 'Fred Moyer <fred@slwifi.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Apache2-Proxy
no_index:
  directory:
    - t
    - inc
requires:
  Compress::Bzip2: 0
  Compress::Zlib: 0
version: 0.04
